name: build

on: [push]

jobs:
  osx:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: create dist dir
        run: mkdir dist
      - name: install tauri command
        run: npm install --save-dev @tauri-apps/cli
      - name: build duoshao project
        run: npm run tauri build
  linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: create dist dir
        run: mkdir dist
      - name: install libdus
        run: |
          sudo apt install libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libssl-dev \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev
      - name: install tauri command
        run: npm install --save-dev @tauri-apps/cli
      - name: build duoshao project
        run: npm run tauri build
    