name: lint

on: [push]

jobs:
  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: create dist dir
        run: mkdir dist
      - name: check npx lint
        run: npx prettier --check "src"
      - name: install clippy
        run: rustup component add clippy
      - name: run clippy
        working-directory: src-tauri
        run: cargo clippy